"""Option A vs B streetscape renders via Gemini image output (Nano Banana).

Illustrative imagery only, labelled as such in the UI. Renders are cached in
process memory per option so a demo never burns free-tier quota on repeats.
Without a GEMINI_API_KEY the endpoints 404 and the UI falls back to the static
files in web/public (generated by api/scripts/gen_renders.py when the key
lands) or hides entirely.
"""

import os

from fastapi import APIRouter, HTTPException
from fastapi.responses import Response

router = APIRouter()

IMAGE_MODEL = "gemini-2.5-flash-image"

PROMPTS = {
    "A": (
        "Photorealistic eye-level streetscape render of a new 8-storey "
        "conventional concrete-and-glass boutique hotel on The Esplanade in "
        "downtown Toronto, summer afternoon, rooftop mechanical units visible, "
        "grey precast facade, street trees, pedestrians. No text or logos."
    ),
    "B": (
        "Photorealistic eye-level streetscape render of a new 8-storey mass "
        "timber boutique hotel on The Esplanade in downtown Toronto, summer "
        "afternoon, warm exposed wood structure and large windows, discreet "
        "rooftop heat-pump units, street trees, pedestrians. No text or logos."
    ),
}

_cache: dict[str, bytes] = {}


def _generate(option: str, api_key: str) -> bytes:
    from google import genai
    from google.genai import types

    client = genai.Client(api_key=api_key)
    response = client.models.generate_content(
        model=IMAGE_MODEL,
        contents=PROMPTS[option],
        config=types.GenerateContentConfig(
            response_modalities=["TEXT", "IMAGE"],
            image_config=types.ImageConfig(aspect_ratio="16:9"),
        ),
    )
    for part in response.parts:
        if part.inline_data is not None:
            return part.inline_data.data
    raise ValueError("no image part in response")


@router.get("/render/{option}")
def render(option: str) -> Response:
    option = option.upper()
    if option not in PROMPTS:
        raise HTTPException(status_code=422, detail="option must be A or B")
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise HTTPException(status_code=404, detail="renders unavailable, no key")
    if option not in _cache:
        try:
            _cache[option] = _generate(option, api_key)
        except Exception as exc:
            raise HTTPException(status_code=502, detail=f"render failed: {exc}")
    return Response(content=_cache[option], media_type="image/png")
